# Generated by Django 3.2.13 on 2022-11-10 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocies', to=settings.AUTH_USER_MODEL),
        ),
    ]
