# Generated by Django 3.2.13 on 2022-11-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_notice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tree_notice',
            field=models.BooleanField(default=True),
        ),
    ]
