# Generated by Django 3.2.13 on 2022-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.BooleanField(default=False),
        ),
    ]
