# Generated by Django 3.2.13 on 2022-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_created',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
