# Generated by Django 3.2.13 on 2022-11-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221110_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
    ]
