# Generated by Django 3.2.13 on 2022-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_card_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_created',
            field=models.BooleanField(default=0),
        ),
    ]
