# Generated by Django 3.2.13 on 2022-11-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221110_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.BigIntegerField(blank=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
