# Generated by Django 3.2.13 on 2022-11-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notice',
            field=models.BooleanField(default=True),
        ),
    ]
