# Generated by Django 3.2.13 on 2022-11-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
