# Generated by Django 3.2.13 on 2022-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notice',
            new_name='notice_note',
        ),
        migrations.AddField(
            model_name='user',
            name='notice_tree',
            field=models.BooleanField(default=True),
        ),
    ]
