# Generated by Django 3.2.13 on 2022-11-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221111_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secession',
            new_name='session',
        ),
    ]
