# Generated by Django 3.2.13 on 2022-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(choices=[('노원구', '노원구'), ('송파구', '송파구')], default='선택', max_length=20),
        ),
    ]
