# Generated by Django 3.2.13 on 2022-11-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='meeting_id',
            new_name='meeting',
        ),
    ]
