# Generated by Django 3.2.13 on 2022-11-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(choices=[('강남구', '강남구'), ('광진구', '광진구'), ('노원구', '노원구'), ('동작구', '동작구'), ('마포구', '마포구'), ('성동구', '성동구'), ('송파구', '송파구'), ('서초구', '서초구'), ('용산구', '용산구'), ('영등포구', '영등포구'), ('용산구', '용산구')], default='선택', max_length=20),
        ),
    ]
