# Generated by Django 3.2.13 on 2022-11-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20221114_0038'),
        ('meetings', '0002_auto_20221114_1020'),
    ]

    operations = [
    ]
