# Generated by Django 3.2.13 on 2022-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(choices=[('강남', '강남'), ('건대', '건대'), ('노원', '노원'), ('대학로', '대학로'), ('부평', '부평'), ('신촌', '신촌'), ('수원', '수원'), ('일산', '일산'), ('종로', '종로'), ('잠실', '잠실'), ('홍대', '홍대'), ('하남', '하남')], default='선택', max_length=20),
        ),
    ]
