# Generated by Django 3.2.13 on 2022-11-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
