# Generated by Django 3.2.13 on 2022-11-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
