# Generated by Django 3.2.13 on 2022-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='chimneys',
            field=models.IntegerField(),
        ),
    ]
