# Generated by Django 3.2.13 on 2022-11-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_groupcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_indiv',
        ),
        migrations.RemoveField(
            model_name='groupcard',
            name='is_indiv',
        ),
    ]
