# Generated by Django 3.2.13 on 2022-11-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='category',
            new_name='is_indiv',
        ),
        migrations.AddField(
            model_name='card',
            name='is_private',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
