# Generated by Django 3.2.13 on 2022-11-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20221119_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcard',
            old_name='userdeco',
            new_name='groupdeco',
        ),
    ]
