# Generated by Django 3.2.13 on 2022-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20221120_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcard',
            name='is_private',
            field=models.BooleanField(blank=True),
        ),
    ]
