# Generated by Django 3.2.13 on 2022-11-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_usercard_chimneys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='ribbons',
            new_name='socks',
        ),
    ]
