# Generated by Django 3.2.13 on 2022-11-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_groupcard_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcard',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupcard',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
