# Generated by Django 3.2.13 on 2022-11-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20221111_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='chimney',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='socks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
