# Generated by Django 3.2.13 on 2022-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20221115_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='chimneys',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='socks',
            field=models.IntegerField(blank=True),
        ),
    ]
