# Generated by Django 3.2.13 on 2022-11-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_auto_20221120_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcomment',
            name='ribbons',
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='socks',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
