# Generated by Django 3.2.13 on 2022-11-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_groupcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcomment',
            name='groupcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.groupcard'),
        ),
    ]
