# Generated by Django 3.2.13 on 2022-11-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20221111_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='chimney',
        ),
    ]
