# Generated by Django 3.2.13 on 2022-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_chimney'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='chimneys',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
