# Generated by Django 3.2.13 on 2022-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_chimneys'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ribbons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
