# Generated by Django 3.2.13 on 2022-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_comment_ribbons'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
