# Generated by Django 3.2.13 on 2022-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_comment_id_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_text',
            field=models.TextField(blank=True),
        ),
    ]
